<?php

namespace SimlepriceBundle\Repository;

/**
 * Matching_productRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchingProductRepository extends \Doctrine\ORM\EntityRepository
{
}
