<?php

namespace SimlepriceBundle\Repository;

/**
 * ProductСompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductСompanyRepository extends \Doctrine\ORM\EntityRepository
{
}
