<?php

namespace SimlepriceBundle\Repository;

/**
 * Product_companyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product_companyRepository extends \Doctrine\ORM\EntityRepository
{
}
